/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 1874792627389fc1d484cdad70f4f394)
interface __BaseEnv_CloudflareEnv {
	HYPERDRIVE?: Hyperdrive;
	ASSETS: Fetcher;
	BARGAIN_ENV: "staging" | "production" | "local";
	BARGAIN_ENABLE_DEMO_HEADERS: "false";
	GOOGLE_API_KEY: string;
	OPENAI_API_KEY: string;
}
declare namespace Cloudflare {
	interface StagingEnv {
		HYPERDRIVE: Hyperdrive;
		ASSETS: Fetcher;
		BARGAIN_ENV: "staging";
		BARGAIN_ENABLE_DEMO_HEADERS: "false";
		GOOGLE_API_KEY: string;
		OPENAI_API_KEY: string;
	}
	interface ProductionEnv {
		HYPERDRIVE: Hyperdrive;
		ASSETS: Fetcher;
		BARGAIN_ENV: "production";
		BARGAIN_ENABLE_DEMO_HEADERS: "false";
		GOOGLE_API_KEY: string;
		OPENAI_API_KEY: string;
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BARGAIN_ENV" | "BARGAIN_ENABLE_DEMO_HEADERS" | "GOOGLE_API_KEY" | "OPENAI_API_KEY">> {}
}
